import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Footer from '@/components/footer/Footer';
import { Inter, Raleway } from 'next/font/google';

const raleway = Raleway({ subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className} suppressHydrationWarning={true}>
        <div className="wrapperGlobal">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
